[http.middlewares]
  [http.middlewares.http_to_https.redirectScheme]
    scheme = "https"
    permanent = true

  [http.middlewares.www_to_non-www.redirectRegex]
    regex = "^https://www.(.*)"
    replacement = "https://${1}"

[http.services.http_to_https]
  [[http.services.http_to_https.loadBalancer.servers]]
    url = "http://127.0.0.1/"

[http.routers]
  [http.routers.http_to_https]
    entryPoints = [ "http" ]
    middlewares = [ "http_to_https" ]
    rule = "HostRegexp(`{host:.+}`)"
    service = "http_to_https"
    priority = 1
