[http.middlewares]
  [http.middlewares.auth.basicAuth]
    usersFile = "/etc/traefik/users"
    realm = "Loadbalancer"

[http.routers]

  [http.routers.traefik]
    entryPoints = [ "https"]
    middlewares = [ "auth", "securityHeaders" ]
    rule = "Host(`traefik.bytecluster0002.bytespeicher.org`)"
    service = "api@internal"
 
    [http.routers.traefik.tls]
      certResolver = "letsencrypt"
