# Redirect freifunk-erfurt.de to erfurt.freifunk.net
[http.middlewares]
  [http.middlewares.redirectFreifunkErfurt.redirectRegex]
    regex = "^https://(www.|)freifunk-erfurt.de/"
    replacement = "https://erfurt.freifunk.net/"

[http.services]
  [http.services.wordpressFreifunkErfurt.loadbalancer]
    [[http.services.wordpressFreifunkErfurt.loadbalancer.servers]]
      url = "http://10.2.0.6:80"

[http.routers]

  [http.routers.wordpressFreifunkErfurt]
    entryPoints = [ "https"]
    middlewares = [ "www_to_non-www", "securityHeaders" ]
    rule = "Host(`erfurt.freifunk.net`) || Host(`www.erfurt.freifunk.net`)"
    service = "wordpressFreifunkErfurt"
 
    [http.routers.wordpressFreifunkErfurt.tls]
      certResolver = "letsencrypt"

  # Router for freifunk-erfurt.de
  [http.routers.freifunkErfurt]
    entryPoints = [ "https"]
    middlewares = [ "redirectFreifunkErfurt", "securityHeaders" ]
    rule = "Host(`freifunk-erfurt.de`) || Host(`www.freifunk-erfurt.de`)"
    service = "wordpressFreifunkErfurt"

    [http.routers.freifunkErfurt.tls]
      certResolver = "letsencrypt"
