[http.middlewares]
  [http.middlewares.redirectOldWordpress.redirectRegex]
    regex = "^https://(makerspace-erfurt.de|bytespeicher.org)(/|/feed/)$"
    replacement = "https://technikkultur-erfurt.de${2}"
  [http.middlewares.redirectOldWordpressContent.redirectRegex]
    regex = "^https://(makerspace-erfurt.de|bytespeicher.org)/(.*)$"
    replacement = "https://old.${1}/${2}"

[http.services.redirectOldWordpress]
  [[http.services.redirectOldWordpress.loadBalancer.servers]]
    url = "http://127.0.0.1/"

[http.routers]
  [http.routers.oldWordpress]
    entryPoints = [ "https" ]
    middlewares = [ "redirectOldWordpress", "redirectOldWordpressContent", "www_to_non-www" ]
    rule = "Host(`bytespeicher.org`) || Host(`www.bytespeicher.org`) || Host(`makerspace-erfurt.de`) || Host(`www.makerspace-erfurt.de`)"
    service = "redirectOldWordpress"

    [http.routers.oldWordpress.tls]
      certResolver = "letsencrypt"
