
# Cacheing Plugin usage after registration in pilot
#  [http.middlewares.my-cache.plugin.cache]
#    path = "/var/lib/traefik/cache"
#    maxExpiry = 86400

[http.services.web]
  [[http.services.monitor.loadBalancer.servers]]
    url = "http://10.10.10.3/"
    
[http.routers]

 [http.routers.web]
    entryPoints = [ "https"]
    rule="Host(`bytespeicher.org`)"
    service="web"
    priority = 100
    [http.routers.web.tls]
    certResolver = "letsencrypt"

 [http.routers.mail]
    entryPoints = [ "https"]
    rule="Host(`mail.bytespeicher.org`) || Host(`smtp.bytespeicher.org`) || Host(`imap.bytespeicher.org`)"
    service="http_to_https"
    priority = 10
 [http.routers.mail.tls]
    certResolver = "letsencrypt"
